# Generated by Django 5.2.6 on 2025-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_headcategory_category_head_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_shoe_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.shoesize'),
        ),
    ]
