# Generated by Django 5.2.6 on 2025-11-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shoesize_product_available_shoe_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shoe_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shoesize'),
        ),
    ]
